- .snippets/code/tutorials/polkadot-sdk/build-a-blockchain/simulate-a-network/node-output-1.html
- .snippets/code/tutorials/polkadot-sdk/build-a-blockchain/simulate-a-network/node-output.html
- .snippets/code/tutorials/polkadot-sdk/build-a-blockchain/simulate-a-network/node-shutdown.html
- tutorials/.pages
- tutorials/polkadot-sdk/.pages
- tutorials/polkadot-sdk/build-a-blockchain/.pages
- tutorials/polkadot-sdk/build-a-blockchain/index.md
- tutorials/polkadot-sdk/build-a-blockchain/simulate-a-network.md
- tutorials/polkadot-sdk/index.md
The "Simulate a Network" page was migrated from the existing Substrate.io Tutorial section: https://docs.substrate.io/tutorials/build-a-blockchain/simulate-network/
> [Substrate.io Migration] Tutorials -> Build a Blockchain -> Simulate a Network

- .editorconfig
This just adds an editor config file that can be used to overwrite default styling preferences implemented by other formatters.
> add an editor config file

- .snippets/code/develop/parachain-devs/get-started/polkadot-sdk/install-deps/termynal-1.html
- .snippets/code/develop/parachain-devs/get-started/polkadot-sdk/install-deps/termynal-2.html
- develop/parachain-devs/get-started/polkadot-sdk/.pages
- develop/parachain-devs/get-started/polkadot-sdk/install-deps.md
The "Install Dependencies" page was migrated from the Wiki:  https://wiki.polkadot.network/docs/build-guides-install-deps
> [Polkadot Wiki Migration] Install Polkadot SDK Dependencies

- .github/scripts/create_issues.py
This PR fixes an indentation bug in the script that creates GitHub issues for outdated repositories. 
Previously, the `create_github_issue` function call was outside the for loop, causing only one issue to be created for the last repository. 
The function call has been correctly indented to ensure an issue is created for each outdated repository in the input JSON file.
> Fix `create_github_issue` function call in check-repositories workflow

- develop/application-devs/interact/.pages
- develop/application-devs/interact/light-clients.md
> **This page is from the [Polkadot Wiki](https://wiki.polkadot.network/docs/build-light-clients), and will be heavily edited, updated, and appropriated as needed.**
Page referenced: https://wiki.polkadot.network/docs/build-light-clients
> [Polkadot Wiki Migration] Using Light Clients 

- polkadot-protocol/introduction/.pages
- polkadot-protocol/introduction/glossary.md
> **This page is from the substrate.io documentation, and will be heavily edited, updated, and appropriated as needed.**
We need a glossary merged (with at least basic terms) so we can link these in other pages.
This includes some terms that may be dated, so we should look to see where to improve or remove.
> [Substrate.io Migration] Glossary

- .snippets/code/develop/parachain-devs/interoperability/hrmp-channels/hrmp-query-output.json
- polkadot-protocol/protocol-components/.pages
- polkadot-protocol/protocol-components/cryptography.md
Migrate "Cryptography" section  from  Substrate.io: https://docs.substrate.io/learn/cryptography/
> [Substrate.io Migration] - Polkadot Protocol > Protocol Components > Cryptography

- .gitignore
This PR adds `.vscode` folder to `.gitignore` to avoid accidentally committing any local config that any contributor might have in their local dev environment
> [Fix] Adding .vscode to .gitignore

- polkadot-protocol/architecture/system-chains/asset-hub.md
This PR does the following:
- creates Asset Hub page for `polkadot-protocol/architecture/system-chains/asset-hub.md`
- uses information from: #21 and #59 plus online resources
> IA update - creates Asset Hub page for Protocol section

- index.md
- js/header-scroll.js
This PR fixes the following:
- Scrolling behavior on Safari. It was pretty jumpy, these changes smooth it out without impacting the scrolling behavior on other browsers
- Removes the index page content for the home page. The home page content is in the `home.html` template in the mkdocs repo, so this is unnecessary and gets overwritten (was added by accident). However, it was also causing issues with the left navigation on smaller screens, next to the home menu option it was showing a TOC icon
> Minor fixes

- .husky/pre-commit
This PR just updates the pre-commit hook to ignore the TOML files that are causing everything to go haywire. This at least avoids skipping the formatting step with `--no-verify` commits
> update pre-commit hook to ignore a few of the toml files

- develop/parachains/get-started/install-polkadot-sdk.md
This PR aims to fix a minor formatting issue in the polkadot sdk installation page:
From:
To:
> [FIX] -  formatting on install polkadot sdk page

- js/root-level-sections.js
This PR just updates the script to work on gh pages so the left navigation is shown on the root level index pages (i.e., https://papermoonio.github.io/polkadot-mkdocs/develop/)
> Update script logic to show left navigation on root level index pages

- develop/smart-contracts/index.md
This PR aims to fix a minor typo in the smart contracts index page
> [Fix] - Typo

- develop/interoperability/xcm-channels.md
- develop/parachains/customize-parachain/add-existing-pallets.md
- develop/parachains/customize-parachain/add-smart-contract-functionality.md
- develop/parachains/customize-parachain/make-custom-pallet.md
- develop/parachains/customize-parachain/pallet-testing.md
- develop/parachains/deployment/generate-chain-specs.md
- develop/parachains/get-started/build-custom-parachains.md
- develop/parachains/get-started/deploy-parachain-to-polkadot.md
- develop/parachains/maintenance/runtime-upgrades.md
- develop/parachains/testing/setup.md
- develop/toolkit/parachains/fork-chains/chopsticks/get-started.md
- develop/toolkit/parachains/spawn-chains/zombienet/get-started.md
- polkadot-protocol/architecture/parachains/consensus.md
- polkadot-protocol/architecture/parachains/overview.md
- polkadot-protocol/architecture/system-chains/asset-hub.md
This PR aims to add a reference to tutorials at the bottom of the pages that can be linked with a tutorial
> [FIX] - Adding references to tutorials

- .snippets/code/tutorials/polkadot-sdk/parachains/connect-to-relay-chain/acquire-a-testnet-slot/deploy-on-paseo-3.html
- develop/toolkit/interoperability/asset-transfer-api/overview.md
This PR corrects a small typo on the asset transfer API overview page
Note: Prettier executed on `.snippets/code/tutorials/polkadot-sdk/parachains/connect-to-relay-chain/acquire-a-testnet-slot/deploy-on-paseo-3.html` also resolves a slight indentation issue
> [FIX] - Typo on asset transfer overview

- js/fix-created-date.js
This just adds a script to default to the last updated date instead of the current date if for whatever reason the created date cannot be found
Goes with PR: https://github.com/papermoonio/polkadot-mkdocs/pull/56
> add script to fix created dates

- develop/index.md
Fix the broken link; otherwise, it redirects to `/develop/tutorials/polkadot-sdk/parachains/zero-to-hero/`, which does not exist
> [FIX] - Broken link

- develop/index.md
- develop/parachains/customize-parachain/index.md
This PR adds a link to Polkadot SDK best practices in the following sections:
Develop Index
Develop > Parachains > Customize your Parachain Index
> Add link to Polkadot SDK best practices

- tutorials/polkadot-sdk/testing/spawn-basic-chain.md
Fix an image and a couple snippets that had an extra slash in them
> fix double slashes

- develop/parachains/intro-polkadot-sdk.md
This PR creates a mermaid diagram for Substrate Node architecture. It demonstrates the separation between the runtime and the client. 
@nhussein11 I got this laid out ok but I'm not having luck applying styles. I was hoping to make the "Substrate Node" text a size bigger and maybe bold? idk. Just doesn't stand out much. Do you want to take a shot at applying styles?
> Create mermaid diagram for Substrate Node

- tutorials/polkadot-sdk/parachains/zero-to-hero/set-up-a-template.md
Problem: Websocket address was presented like it should be copied (which implied it needs to be pasted, which leads down a rabbit hole...). Instead moved it to inline, so that the instruction is clearly to open Polkadot app
> Minor fix: Moved to inline from being copyable

- polkadot-protocol/architecture/polkadot-chain/agile-coretime.md
This PR creates a small mermaid diagram to describe the two types of coretime for /polkadot-protocol/architecture/polkadot-chain/agile-coretime
> Create mermaid diagram for Coretime

- .github/env
- .github/workflows/checks.yml
- .github/workflows/reusable-preflight.yml
* This PR adds Github workflows for some basic checks.
* This is required as we are trying to make all the rust code in this repository buildable and testable as part of [this issue](https://github.com/polkadot-developers/polkadot-docs/issues/236). These workflows would streamline the review process by performing some basic checks like `build`, `test` and `fmt`. These tests are largely inspired by what is already present in the `polkadot-sdk`.
* This uses the same docker image for the environment as the `polkadot-sdk` repository for consistency.
* Given that the code in this repository is exclusively for the tutorials on docs.polkadot.com, I have added the minimum tests required (IMO) to make reviews streamlined and easy. More tests can be added later on if required.
* **Testing**: Used …
> add github workflows

- .snippets/code/README.md
- .snippets/code/rust-toolchain.toml
Small PR to add rust toolchain information to ensure consistent builds. The rust versions are the same as the `polkadot-sdk` package.
> add rust toolchain information

- .CONTRIBUTING.md
- .github/workflows/checks.yml
- tutorials/polkadot-sdk/parachains/zero-to-hero/add-pallets-to-runtime.md
Since now we are pulling in templates, they bring in features which are not fully implemented in the custom pallet leading to build errors. Removing `--all-features` from `clippy` to allow for successful CI checks.
Issue identified in #302 
Part of #236
> remove clippy check for all features

- infrastructure/running-a-validator/onboarding-and-offboarding/set-up-validator.md
- variables.yml
This page addresses some issues in the `Set Up a Validator` page
> Improve Set Up Validator

- develop/parachains/intro-polkadot-sdk.md
This PR adds a first draft mermaid diagram for the FRAME section. 
@nhussein11 can you improve this one as well? I'm not sure how I feel about this current version.
> Create mermaid diagram for FRAME section

- develop/interoperability/test-and-debug.md
Refactor XCM Testing and Debugging page and remove XCM Simulator
> Refactor Develop -> Interoperabiity -> Testing and Debugging

- infrastructure/running-a-validator/operational-tasks/general-management.md
This PR cleans up the following page: https://docs.polkadot.com/infrastructure/running-a-validator/operational-tasks/general-management/
In particular it does the following:
- Makes the list items concise
- Formats each of the lists in the same way
- Updates usage of Alertmanager, so we're not using unnecessary backticks
> clean up the general management docs

- develop/parachains/deployment/generate-chain-specs.md
- develop/parachains/deployment/index.md
- develop/parachains/testing/benchmarking.md
- develop/parachains/testing/mock-runtime.md
This PR makes the following changes:
Removes instances of using admonitions for cross-references
Updates instances of improper messaging admonition usage
For these pages:
-develop/parachains testing, deployment, and maintenance (all pages in these sections
To align with new style guide standards for admonitions.
> develop/parachains testing, deployment, maintenance admo

- develop/smart-contracts/index.md
- develop/smart-contracts/overview.md
- develop/smart-contracts/wasm-ink.md
This PR makes the following changes:
Removes instances of using admonitions for cross-references
Updates instances of improper messaging admonition usage
For these pages:
-develop/smart-contracts (all pages in this section)
To align with new style guide standards for admonitions.
> updates admos for dev/smart contracts

- .snippets/code/develop/smart-contracts/evm-toolkit/ethers-js/checkStorage.js
- .snippets/code/develop/smart-contracts/evm-toolkit/ethers-js/compile.js
- .snippets/code/develop/smart-contracts/evm-toolkit/ethers-js/deploy.js
- .snippets/code/develop/smart-contracts/evm-toolkit/ethers-js/fetchLastBlock.js
- develop/smart-contracts/.pages
- develop/smart-contracts/json-rpc-apis.md
This PR adds the JSON RPC APIs page to the asset hub smart contracts section
> Create "JSON-RPC APIs (Eth Compatibility)" page

- .snippets/code/develop/smart-contracts/evm-toolkit/ethers-js/checkStorage.js
- .snippets/code/develop/smart-contracts/evm-toolkit/ethers-js/compile.js
- .snippets/code/develop/smart-contracts/evm-toolkit/ethers-js/deploy.js
- .snippets/code/develop/smart-contracts/evm-toolkit/ethers-js/fetchLastBlock.js
- .snippets/code/develop/smart-contracts/native-evm-contracts/ether-js-server-connection.js
- .snippets/code/tutorials/interoperability/xcm-transfers/from-relaychain-to-parachain/reserve-backed-transfer.js
- .snippets/code/tutorials/polkadot-sdk/testing/spawn-basic-chain/connect-to-alice-01.js
- develop/smart-contracts/json-rpc-apis.md
This PR reformats the JSON RPC page as follows:
- Removes the section categorization because I feel like people are going to use this page as a quick reference so it should just be alphabetized so users can more easily find what they're looking for
- Sets the section headers to be the rpc method name for the same reason as above
- Defines parameters even when there are none and sets the parameter types along with links back to the Ethereum docs for more info on data, quantities, and default block parameters
- Moves the examples out of admonitions, as they shouldn't be hidden or be highlighted. Especially since the main purpose of this page is to showcase what's available along with quick copy/paste examples
Looks like people have been skipping the formatter cause a bunch of pages were …
> Update the layout of the JSON RPC page

- .husky/pre-commit
- llms.txt
In https://github.com/polkadot-developers/polkadot-docs/pull/390, we've noticed that the pre-commit hook takes too long to execute because the formatters (mainly Taplo) check every file, even if they are already correctly formatted.  
We can leverage `git diff --cached` to apply the pre-commit hook only to files that have changed, significantly reducing the commit time.
> [FIX] - Pre-commit hook over staged files

- .github/workflows/check-url-changes.yml
Adds a GitHub Action workflow that detects when documentation files are deleted or renamed in PRs to prevent broken links and 404s for users. The workflow automatically posts a warning in PRs that looks like this:
🔍 **Documentation URL Checker**
This PR modifies documentation files in ways that could potentially create broken links.
**Deleted markdown files:**
```
develop/networks.md
```
**Renamed markdown files:**
```
tutorials/polkadot-sdk/testing/fork-live-chains.md -> develop/toolkit/parachains/fork-chains/chopsticks/fork-live-chains.md
tutorials/interoperability/xcm-channels/index.md -> tutorials/interoperability/hrmp-channels/index.md
tutorials/interoperability/xcm-channels/para-to-para.md -> tutorials/interoperability/hrmp-channels/para-to-para.md …
```
> Add workflow to detect url changes

- tutorials/polkadot-sdk/parachains/zero-to-hero/set-up-a-template.md
Installation command was found to be broken, see https://github.com/paritytech/polkadot-sdk/issues/7653#issuecomment-2678085930  
Changed it to use crates-io registry. How is the version locking in this repo working? The template does not have a version?
> Fix cargo install omni node

- variables.yml
Update the omni node variable, so it matches what the the tutorial expects (`cargo install polkadot-omni-node@{{dependencies.crates.polkadot_omni_node.version}}`): https://github.com/polkadot-developers/polkadot-docs/pull/444/files#diff-d5405921056a533696168f2b519d4313487cd6ceec6f4cc762715d0750c1a1fcR52
> update omni node variable

- infrastructure/running-a-validator/onboarding-and-offboarding/set-up-validator.md
- llms.txt
This PR updates the package manager installation section by removing the RPM-based instructions and focusing exclusively on Debian-based distributions. Solves #459
> Remove RPM Installation Instructions

- develop/interoperability/xcm-runtime-apis.md
- llms.txt
Remote code snippets were using the wrong tag
> Fix Remote Snippets in XCM Runtime APIs

- scripts/generate_llms.py
This updates the `generate_llms.py` script to also ignore `venv`
> update llms script to ignore venv

- llms.txt
- tutorials/polkadot-sdk/parachains/zero-to-hero/set-up-a-template.md
Issue reported in https://app.element.io/#/room/%23substratedevs:matrix.org
Need to install with locked to avoid this: https://substrate.stackexchange.com/questions/12302/compile-error-multiple-impls-satisfying-u32/12303#12303
Basically, `cargo install` without `--locked` can break without warning. Maybe worth reviewing the other usage as well.
> Install with `--locked`

- tutorials/smart-contracts/deploy-erc20.md
- tutorials/smart-contracts/deploy-nft.md
- tutorials/smart-contracts/launch-your-first-project/create-contracts.md
- tutorials/smart-contracts/launch-your-first-project/test-and-deploy-with-hardhat.md
This PR introduces difficulty badges to the smart contracts tutorial sections, which will be shown in cards on both the index and content pages
It needs to be merged with the following: https://github.com/papermoonio/polkadot-mkdocs/pull/86
> add difficulty badges to smart contracts

- llms.txt
- polkadot-protocol/smart-contract-basics/overview.md
This PR fixes https://github.com/polkadot-developers/polkadot-docs/issues/543, by removing the reference to "Substrate" and just leaving "smart contracts"
> [SC Feedback] - Remove/Rename stackexchange reference from the docs

- develop/smart-contracts/json-rpc-apis.md
- llms.txt
This PR fixes the endpoint used in https://papermoonio.github.io/polkadot-mkdocs/develop/smart-contracts/json-rpc-apis/, since when executing an eth request to https://westend-asset-hub-rpc.polkadot.io it would not work. Instead, the proper endpoint to use when calling eth methods is - https://westend-asset-hub-eth-rpc.polkadot.io.
> [FIX] - Rollback json rpc api endpoint

- llms.txt
- tutorials/polkadot-sdk/parachains/zero-to-hero/set-up-a-template.md
The parachain-template was [recently updated](https://github.com/paritytech/polkadot-sdk-parachain-template/issues/24#issuecomment-2815076325) to use the stable-2412 release, which introduces changes that are not yet reflected in the Zero-to-Hero pallet tutorial.
This PR temporarily pins the template to a known working commit (ecaf71d) to ensure the tutorial remains functional while we work on updating the docs to match the latest changes.
> Apply temporary fix to Set Up a Template tutorial

- tutorials/polkadot-sdk/parachains/zero-to-hero/set-up-a-template.md
attempt to fix #534 
Since this is a most basic tutorial to start a Parachain, most likely no visitor is in a position to immediately learn about the right flags for production ready compilation. Instead I suggest to remove the misleading wording and simply mention that ``--release`` yields a binary for improved runtime performance compared to a regular (debug) build.
> update build flag tip

- .snippets/code/develop/smart-contracts/dev-environments/hardhat/disclaimer-json-rpc-provider-alternative.js
- develop/smart-contracts/dev-environments/hardhat.md
- llms.txt
This PR complements the hardhat disclaimer regarding code size limitations, explaining the alternative JsonRPCProvider as stated in https://github.com/paritytech/contract-issues/issues/47#issuecomment-2872146946
> [FIX] - Hardhat disclaimer in SC

- .snippets/code/develop/smart-contracts/dev-environments/hardhat/hardhat.config.js
- .snippets/code/develop/smart-contracts/dev-environments/hardhat/interact.js
- develop/smart-contracts/dev-environments/hardhat.md
- llms.txt
- variables.yml
This PR is a follow up of #563
> [FIX] - Update hardhat guide according to latest releases of hardhat-polkadot

- develop/smart-contracts/dev-environments/hardhat.md
- llms.txt
Fixing highlights in hardhat guide snippets and enhancing the Binary Configuration section with a clear disclaimer on binary paths.
> [FIX]- adding Hardhat binary configuration section and path instructions

- .snippets/text/tutorials/polkadot-sdk/parachains/zero-to-hero/zero-to-hero-timeline.json
- llms.txt
- tutorials/polkadot-sdk/parachains/zero-to-hero/index.md
This PR adds the timeline element to the parachains zero-to-hero index page to replace the In This Section cards.  To view locally, use with [mkdocs PR 83](https://github.com/papermoonio/polkadot-mkdocs/pull/83)
> adds timeline element to parachain zero to hero index page, updates llms

- llms.txt
- polkadot-protocol/smart-contract-basics/evm-vs-polkavm.md
This PR updates the [EVM vs PolkaVM](https://papermoonio.github.io/polkadot-mkdocs/polkadot-protocol/smart-contract-basics/evm-vs-polkavm/) page to incorporate the latest in https://contracts.polkadot.io/differences_to_eth
> [FIX] - Evm vs polka vm page update

- .snippets/text/smart-contracts/code-size.md
- develop/smart-contracts/dev-environments/hardhat.md
- develop/smart-contracts/dev-environments/remix.md
- develop/smart-contracts/libraries/ethers-js.md
- develop/smart-contracts/libraries/viem.md
- develop/smart-contracts/libraries/web3-js.md
- llms.txt
This PR adds some quick fixes before SC launch:
- Add a prominent note about the 100kb contract size limit in SC docs
> [FIX] -  Quick fixes before SC launch

- llms.txt
- tutorials/polkadot-sdk/parachains/zero-to-hero/.pages
- tutorials/polkadot-sdk/parachains/zero-to-hero/add-pallets-to-runtime.md
- tutorials/polkadot-sdk/parachains/zero-to-hero/build-custom-pallet.md
- tutorials/polkadot-sdk/parachains/zero-to-hero/pallet-benchmarking.md
- tutorials/polkadot-sdk/parachains/zero-to-hero/pallet-unit-testing.md
This PR fixes the zero to hero:
- Reorders the steps to add the pallet to the runtime before benchmarking, or it breaks
- Fixes snippets and highlights accordingly
- Pins the frame-omni-bencher to version 0.10.0 to prevent `error[E0432]: unresolved import sc_network_types::kad`
This is needed to work on https://github.com/polkadot-developers/polkadot-docs/issues/689
> [FIX] - Zero to hero tutorials

- develop/smart-contracts/.pages
- develop/smart-contracts/connect-to-kusama.md
- js/connect-to-metamask.js
- llms.txt
This pull request introduces support for connecting to Kusama Hub, a live production environment for deploying smart contracts. It includes updates to documentation, code, and configuration files to integrate Kusama Hub into the developer workflow.
* Added a new page, `connect-to-kusama.md`, detailing how to connect to Kusama Hub, including network specifications, deployment considerations, and next steps for developers. [[1]](diffhunk://#diff-150051690a6e5630e9981bc2e82d889814e12e66ceb828fc1620ff6b7804f12fR1-R87) [[2]](diffhunk://#diff-f43a9e2f7da89777ca234fc2f236252b27a44652586c9514b243e81bf1b19114R6863-R6954)
* Updated the navigation in `develop/smart-contracts/.pages` to include the new "Connect to Kusama" section.
* Added references to the new documentation page in `llms.txt`.
* …
> [Add] - connect to kusama page

- llms.txt
- tutorials/polkadot-sdk/parachains/zero-to-hero/deploy-to-testnet.md
This pull request updates documentation to reflect the deprecation of the `para_id` field in Polkadot SDK chain specifications. It introduces guidance for transitioning to the new runtime API using the `GetParachainInfo` trait.
**_DISCLAIMER_**: This PR uses the following url: `tutorials/polkadot-sdk/parachains/zero-to-hero/runtime-upgrade` which is introduced by https://github.com/polkadot-developers/polkadot-docs/pull/760
* [`llms.txt`](diffhunk://#diff-f43a9e2f7da89777ca234fc2f236252b27a44652586c9514b243e81bf1b19114R32503-R32511): Added a note explaining the upcoming removal of the `para_id` field in chain specifications starting with Polkadot SDK release `stable2512`. It provides details on updating runtimes to implement the `cumulus_primitives_core::GetParachainInfo` trait and links …
> [FIX] - update deploy-to-testnet.md to note deprecation of `para_id` in chain specs

- llms.txt
- tutorials/polkadot-sdk/parachains/zero-to-hero/obtain-coretime.md
Merging https://github.com/polkadot-developers/polkadot-docs/pull/792
This pull request updates documentation related to purchasing bulk coretime by consolidating information about user interfaces and removing redundant references to the Lastic Coretime Marketplace.
Documentation updates:
* [`llms.txt`](diffhunk://#diff-f43a9e2f7da89777ca234fc2f236252b27a44652586c9514b243e81bf1b19114L33039-R33039): Simplified the description of purchasing bulk coretime by consolidating the RegionX Coretime Marketplace as the primary user interface and removing references to the Lastic Coretime Marketplace.
* [`tutorials/polkadot-sdk/parachains/zero-to-hero/obtain-coretime.md`](diffhunk://#diff-fb836973dea4e15a1c885da1e38145c19330d6f0127d4355d08c31919e7d4abbL51-R51): Updated the tutorial to align with the …
> Remove mention of Lastic

- .github/workflows/check-pr-labels.yml
This PR goes with https://github.com/papermoonio/workflows/pull/5
This pull request adds a new GitHub Actions workflow to ensure proper labeling of pull requests. The workflow leverages a reusable workflow to check for documentation-related labels.
* [`.github/workflows/check-pr-labels.yml`](diffhunk://#diff-246a758f4f4b88200b9c146ac52277a7f5f8da296a9ad88b6be7b079a174b1c7R1-R13): Introduced a new workflow named "Check PR Labels" that uses the reusable `pr-blocked-label.yml` workflow to validate PR labels related to documentation. It includes parameters for repositories and URLs for documentation checks.
> Adding pr label checker

- infrastructure/staking-mechanics/offenses-and-slashes.md
- llms.txt
Resolves https://github.com/polkadot-developers/polkadot-docs/issues/789
This pull request updates documentation in two files, `infrastructure/staking-mechanics/offenses-and-slashes.md` and `llms.txt`, to reflect changes in the staking mechanics and penalties for validator infractions. The updates primarily focus on aligning the material with Stage 4 changes and refining the details of penalties and priorities.
* **Stage Update:**
- Updated references from Stage 2 to Stage 4 to reflect the latest changes in the disabling mechanism. (`infrastructure/staking-mechanics/offenses-and-slashes.md` - [[1]](diffhunk://#diff-642b3f70d3fe4003f798bf0afa641762a92ede84316dceb387f6208cc89623d7L160-R160) `llms.txt` - [[2]](diffhunk://#diff-f43a9e2f7da89777ca234fc2f236252b27a44652586c9514b243e81bf1b19114L2 …
> Update Penalties by Offenses

- infrastructure/running-a-validator/onboarding-and-offboarding/set-up-validator.md
- llms.txt
Fix 'Install with Package Managers' section by referencing the new release-team@parity.io key
> Update GPG Key to release-team@parity.io

- develop/smart-contracts/connect-to-kusama.md
- develop/smart-contracts/connect-to-polkadot.md
- llms.txt
- polkadot-protocol/smart-contract-basics/accounts.md
Fixes https://github.com/polkadot-developers/polkadot-docs/issues/822
This pull request introduces documentation updates to explain the process of mapping native Polkadot accounts for Ethereum compatibility. The changes add warnings and detailed instructions across multiple files to guide users on enabling compatibility for accounts created with Polkadot/Substrate keypairs.
* **General Warnings on Account Mapping**:
- Added warnings in `connect-to-kusama.md`, `connect-to-polkadot.md`, and `llms.txt` to inform users that native Polkadot accounts (32-byte format) must be mapped for Ethereum compatibility. Links to the detailed "Account Mapping" section are included. [[1]](diffhunk://#diff-150051690a6e5630e9981bc2e82d889814e12e66ceb828fc1620ff6b7804f12fR19-R20) …
> [FIX] - Adding disclaimer for accounts

- develop/smart-contracts/dev-environments/hardhat.md
- llms.txt
- tutorials/smart-contracts/launch-your-first-project/test-and-deploy-with-hardhat.md
Note: this PR does not include the new Docker feature due to issues with 0.1.9. Once hardhat-polkadot 0.1.10 is released, we will add documentation for that feature.
This pull request updates the Hardhat development environment documentation and related tutorial files to use the latest `@parity/hardhat-polkadot` plugin version and the latest example code from the `polkavm-hardhat-examples` repository. It also clarifies `.gitignore` instructions and adds a warning about the default network forking behavior in Hardhat.
Dependency and example updates:
* Updated all installation instructions and code references to use `@parity/hardhat-polkadot@0.1.9` instead of `0.1.8` and updated repository/example links and code snippets to use `v0.0.8` instead of `v0.0.7`. …
> [FIX] - Update hardhat guides to `hardhat-polkadot` 1.9.0

- develop/parachains/maintenance/runtime-upgrades.md
- llms.txt
This pull request updates the documentation for storage migrations to provide a clearer and more concise explanation. The changes focus on improving readability and directing users to more detailed resources, while removing redundant and overly detailed explanations from the main text.
Documentation improvements:
* Rewrote the introduction to storage migrations to be more concise and beginner-friendly, clarifying what storage migrations are and why they are necessary. [[1]](diffhunk://#diff-529df31a01dc6500310a4a2fc0db4979db40c427f031791c76f5b59bd4194989L52-R54) [[2]](diffhunk://#diff-f43a9e2f7da89777ca234fc2f236252b27a44652586c9514b243e81bf1b19114L5921-R5923)
* Removed detailed implementation and ordering instructions, instead linking to the dedicated storage migrations documentation …
> [FIX] - Duplicated storage migration content

- .snippets/code/develop/toolkit/parachains/remote-proxies/remote-proxy-example.js
- develop/toolkit/parachains/.nav.yml
- develop/toolkit/parachains/remote-proxies.md
- llms.txt
Resolves https://github.com/polkadot-developers/polkadot-docs/issues/610
This pull request introduces a new feature for implementing remote proxies in the Polkadot ecosystem, specifically for the Kusama network and its parachains. It includes a detailed guide, an example implementation script, and updates to the documentation navigation to reflect the new feature.
* **Example Script**: Added a complete implementation of a remote proxy transaction in `remote-proxy-example.js`. This script demonstrates how to connect to the Kusama relay chain and Asset Hub, generate cryptographic storage proofs, and construct a remote proxy transaction.
* **Documentation Guide**: Created a comprehensive guide in `remote-proxies.md` explaining the architecture, workflow, and practical implementation of …
> Add guide for remote proxy implemention

- ai-chatbot-policy.md
Add the AI Chatbot policy to the docs.
This goes with Mkdocs PR, which adds a link to this page to the footer: https://github.com/papermoonio/polkadot-mkdocs/pull/116
> add AI chatbot policy to docs

- develop/interoperability/send-messages.md
- develop/interoperability/xcm-guides/from-apps/transfers.md
- develop/networks.md
- develop/parachains/deployment/obtain-coretime.md
- develop/parachains/index.md
- develop/parachains/maintenance/runtime-metrics-monitoring.md
- develop/smart-contracts/dev-environments/remix.md
- develop/smart-contracts/faqs.md
- llms-files/llms-basics.txt
- llms-files/llms-dapps.txt
- llms-files/llms-infrastructure.txt
- llms-files/llms-networks.txt
- llms-files/llms-parachains.txt
- llms-files/llms-polkadot-protocol.txt
- llms-files/llms-smart-contracts.txt
- llms-files/llms-tooling.txt
- llms-full.txt
- polkadot-protocol/architecture/system-chains/overview.md
- polkadot-protocol/parachain-basics/accounts.md
This pull request consists of minor corrections across multiple documentation files, primarily focusing on fixing spelling errors and improving word choice for clarity and professionalism. These changes help ensure the documentation is accurate and easier to read.
Spelling and Typo Corrections:
* Fixed spelling errors such as "acheive" to "achieve", "succesfully" to "successfully", "enviroment" to "environment", "paricipants" to "participants", "transaltion" to "translation", and "specifc" to "specific" in various documentation files. [[1]](diffhunk://#diff-441049b2a2b889a91a4c2715d41c57308835645718d465e4d2b2fd396d363b72L18-R22) [[2]](diffhunk://#diff-ad3d0a0d5d15fa209adc506b34951ae835f861cae0d4775943489670290aeabaL82-R82) [[3]](diffhunk://#diff-a38ed68dc8b41aee55ed881348438435df658e23ccaf …
> [FIX] - typos across the docs
