.github/workflows/vale.yml
DO NOT MERGE until [PR in mkdocs](https://github.com/papermoonio/polkadot-mkdocs/pull/3) is merged.
This PR introduces a GitHub Action workflow that automatically performs Vale document reviews on pull requests targeting the master branch.
Utilizes the reusable Vale review workflow from the papermoonio/polkadot-mkdocs repository.
=> Add vale gh action

.github/workflows/vale.yml
Remove description field from workflow
=> Remove description from vale workflow

infrastructure/validators/.pages, infrastructure/validators/build-a-community.md
> This page was migrated from https://wiki.polkadot.network/docs/maintain-guides-validator-community
=> [Polkadot Wiki Migration] Build a Community

polkadot-protocol/onchain-governance/.pages
This pr  fixs the mapping of tracks origin page in the on chain governance section
=> [Fix] - solving mapping of tracks-origin.md

.snippets/code/develop/blockchains/testing/setup/genesis-config-custom.rs, .snippets/code/develop/blockchains/testing/setup/genesis-config.rs, .snippets/code/develop/blockchains/testing/setup/integration-testing-module.rs, develop/blockchains/testing/setup.md
This PR aims to add the setup page for the testing section of Develop
=> Develop > Testing > Setup

develop/integrations/.pages, develop/integrations/indexers.md, develop/integrations/oracles.md, develop/integrations/others.md, develop/integrations/wallets.md
This page aims to add the integrations section
=> Add Develop->Integrations section

.snippets/code/develop/blockchains/testing/runtime/full-integration-test.rs, .snippets/code/develop/blockchains/testing/runtime/pallet-a-integration-test.rs, .snippets/code/develop/blockchains/testing/runtime/pallet-b-call.rs, .snippets/code/develop/blockchains/testing/runtime/pallet-b-integration-test.rs, .snippets/code/develop/blockchains/testing/runtime/pallet-coupling.rs, develop/blockchains/testing/runtime.md
This PR aims to add the runtime page for the testing section of Develop
=> Develop > Testing > Runtime

.snippets/code/develop/blockchains/maintenance/storage-migrations/example-1.rs, .snippets/code/develop/blockchains/maintenance/storage-migrations/example-2.rs, .snippets/code/develop/blockchains/maintenance/storage-migrations/example-3.rs, .snippets/code/develop/blockchains/maintenance/storage-migrations/example-4.rs, .snippets/code/develop/blockchains/maintenance/storage-migrations/executive.rs, .snippets/code/develop/blockchains/maintenance/storage-migrations/on-runtime-upgrade-trait.rs, develop/blockchains/maintenance/storage-migrations.md
This PR aims to add the "Storage Migrations" page to the "Maintenance" section of Develop
=> Maintenance -> Storage Migrations

.snippets/code/develop/toolkit/api-libraries/papi/api-instantiation-smoldot-nodejs.ts, .snippets/code/develop/toolkit/api-libraries/papi/api-instantiation-smoldot-webworker.ts, .snippets/code/develop/toolkit/api-libraries/papi/api-instantiation-smoldot.ts, .snippets/code/develop/toolkit/api-libraries/papi/api-instantiation-wss.ts, .snippets/code/develop/toolkit/api-libraries/papi/send-tx-transfer-keep-alive.ts, develop/toolkit/api-libraries/papi.md
This page aims to add the PAPI library
=>  API Libraries > Polkadot API (PAPI)

.snippets/code/develop/toolkit/api-libraries/sidecar/asset-hub-node-version-response.md, .snippets/code/develop/toolkit/api-libraries/sidecar/get-node-version.md, .snippets/code/develop/toolkit/api-libraries/sidecar/terminal-output.md, develop/toolkit/api-libraries/sidecar.md
This page aims to add the Sidecar REST API
=> API Libraries > Sidecar REST API

.snippets/code/develop/toolkit/api-libraries/polkadot-js-sdk/api-instance.js, .snippets/code/develop/toolkit/api-libraries/polkadot-js-sdk/read-constants.js, .snippets/code/develop/toolkit/api-libraries/polkadot-js-sdk/read-state.js, .snippets/code/develop/toolkit/api-libraries/polkadot-js-sdk/send-txs.js, develop/toolkit/api-libraries/.pages, develop/toolkit/api-libraries/polkadot-js-api.md, develop/toolkit/api-libraries/polkadot-js-sdk.md
This page aims to add the Polkadot.js API
=> API Libraries > Polkadot.js API

.snippets/code/develop/toolkit/api-libraries/py-substrate-interface/read_state.py, .snippets/code/develop/toolkit/api-libraries/py-substrate-interface/send_tx.py, .snippets/code/develop/toolkit/api-libraries/py-substrate-interface/substrate_interface.py, develop/toolkit/api-libraries/py-substrate-interface.md
This page aims to add the Python Substrate Interface page
=> API Libraries > Python Substrate Interface

infrastructure/running-a-validator/onboarding-and-offboarding/stop-validating.md
This PR: adds content for Infrastructure > Onboarding & Offboarding > Stop Validating to align with updated IA.
=> adds stop validating content for new IA

polkadot-protocol/architecture/system-chains/bridge-hub.md
Adds high level documentation of the functionality and components that make up the BridgeHub system chain
=> Polkadot Protocol > Architecture > System Chains > BridgeHub

polkadot-protocol/architecture/system-chains/coretime.md, polkadot-protocol/glossary.md
Describes the purpose and primary functions of the Coretime chain, along with relevant RFCs
=> Polkadot Protocol > Architecture > System Chains > Coretime

develop/development-pathways/index.md
This PR creates the "Development Pathways" page
=> Develop > Development Pathways

polkadot-protocol/basics/.pages, polkadot-protocol/basics/interoperability.md
This PR aims to add the Interoperability page in the Basics section
=> Basics > Interoperability

develop/integrations/indexers.md, develop/integrations/oracles.md, develop/integrations/wallets.md
This PR removes the placeholder icons from the integration pages. We can worry about adding the brand logos instead after launch
=> remove icons from integration pages

.snippets/code/develop/toolkit/interoperability/asset-transfer-api/overview/localParachainTx.md, .snippets/code/develop/toolkit/interoperability/asset-transfer-api/overview/localParachainTx.ts, .snippets/code/develop/toolkit/interoperability/asset-transfer-api/overview/paraToPara.md, .snippets/code/develop/toolkit/interoperability/asset-transfer-api/overview/paraToPara.ts, .snippets/code/develop/toolkit/interoperability/asset-transfer-api/overview/relayToSystem.md, .snippets/code/develop/toolkit/interoperability/asset-transfer-api/overview/relayToSystem.ts, .snippets/code/develop/toolkit/interoperability/asset-transfer-api/overview/setup.ts, .snippets/code/develop/toolkit/interoperability/asset-transfer-api/reference/asset-transfer-type.md, .snippets/code/develop/toolkit/interoperability/asset-transfer-api/reference/ca-example-request.ts, .snippets/code/develop/toolkit/interoperability/asset-transfer-api/reference/ca-example-response.md, .snippets/code/develop/toolkit/interoperability/asset-transfer-api/reference/ca-fn-signature.ts, .snippets/code/develop/toolkit/interoperability/asset-transfer-api/reference/constructed-format.md, .snippets/code/develop/toolkit/interoperability/asset-transfer-api/reference/ctt-example-request.ts, .snippets/code/develop/toolkit/interoperability/asset-transfer-api/reference/ctt-example-response.md, .snippets/code/develop/toolkit/interoperability/asset-transfer-api/reference/ctt-fn-signature.ts, .snippets/code/develop/toolkit/interoperability/asset-transfer-api/reference/de-example-request.ts, .snippets/code/develop/toolkit/interoperability/asset-transfer-api/reference/de-example-response.md, .snippets/code/develop/toolkit/interoperability/asset-transfer-api/reference/de-fn-signature.ts, .snippets/code/develop/toolkit/interoperability/asset-transfer-api/reference/ffi-example-request.ts, .snippets/code/develop/toolkit/interoperability/asset-transfer-api/reference/ffi-example-response.md, .snippets/code/develop/toolkit/interoperability/asset-transfer-api/reference/ffi-fn-signature.ts, .snippets/code/develop/toolkit/interoperability/asset-transfer-api/reference/format.ts, .snippets/code/develop/toolkit/interoperability/asset-transfer-api/reference/transfer-arg-opts.md, .snippets/code/develop/toolkit/interoperability/asset-transfer-api/reference/tx-result.md, develop/toolkit/interoperability/.pages, develop/toolkit/interoperability/asset-transfer-api/.pages, develop/toolkit/interoperability/asset-transfer-api/index.md, develop/toolkit/interoperability/asset-transfer-api/overview.md, develop/toolkit/interoperability/asset-transfer-api/reference.md
This PR aims to add back the asset-transfer-api docs
=> Develop > Toolkit > Interoperability > Asset Transfer API

infrastructure/running-a-node/index.md, infrastructure/running-a-validator/index.md, infrastructure/running-a-validator/onboarding-and-offboarding/index.md, infrastructure/running-a-validator/operational-tasks/index.md, infrastructure/staking-mechanics/index.md, polkadot-protocol/architecture/index.md, polkadot-protocol/architecture/parachains/index.md, polkadot-protocol/architecture/polkadot-chain/index.md, polkadot-protocol/architecture/system-chains/index.md, polkadot-protocol/basics/blocks-transactions-fees/index.md, polkadot-protocol/basics/index.md, polkadot-protocol/index.md, polkadot-protocol/onchain-governance/index.md
This PR just adds meta descriptions for the Polkadot Protocol and Infrastructure sections.
=> infrastructure and protocol index page meta descriptions

develop/parachain-devs/system-parachains/register-a-foreign-asset.md, infrastructure/running-a-validator/onboarding-and-offboarding/stop-validating.md
=> Fix a couple relative links

README.md
Updates Readme with the correct disclaimer
=> README -> Update Disclaimer

develop/blockchains/deployment/.pages, develop/blockchains/deployment/obtain-coretime.md
Add Obtain Coretime Page under Develop > Blockchains > Deployment section
=> Develop > Blockchains > Deployment > Obtain Coretime

infrastructure/index.md, infrastructure/running-a-node/index.md, infrastructure/running-a-node/setup-full-node.md, infrastructure/running-a-validator/index.md, infrastructure/running-a-validator/onboarding-and-offboarding/index.md, infrastructure/running-a-validator/operational-tasks/index.md, infrastructure/staking-mechanics/index.md
This PR adds more content and external links to the index pages in the infrastructure section 🚀
=> Customize the infrastructure index pages

polkadot-protocol/architecture/parachains/consensus.md
This PR aims to split the long mermaid diagram of the consensus page
=> [Fix] - Consensus page mermaid diagram

develop/interoperability/send-messages.md, develop/toolkit/interoperability/xcm-tools.md, polkadot-protocol/architecture/system-chains/overview.md, polkadot-protocol/basics/accounts.md, tutorials/interoperability/xcm-channels/para-to-para.md, tutorials/interoperability/xcm-channels/para-to-system.md, tutorials/polkadot-sdk/parachains/connect-to-relay-chain/prepare-parachain.md
=> Fix Broken Links

polkadot-protocol/onchain-governance/origins-tracks.md
=> Fix note in Polkadot Protocol > Onchain Governance > Origins and Tracks

.github/workflows/check-mkdocs-build.yml
This pr adds the workflow for mkdocs build
=> add mkdocs build workflow

.github/workflows/check-mkdocs-build.yml
This PR aims to fix a minor typo in the "check-mkdocs-build.yml" workflow
=> [FIX] - mkdocs build workflow typo

develop/smart-contracts/evm/.pages, develop/smart-contracts/evm/index.md, develop/smart-contracts/index.md, develop/smart-contracts/overview.md
This PR hides the "PolkaVM" instances and adds a banner clarifying that some updates will be introduced in the landscape of polakdot smart contracts
Closes #240
=> [FIX] - Add smart contracts banner

infrastructure/staking-mechanics/rewards-payout.md
This PR updates mermaid diagrams using block-beta type to use flowchart type to fix rendering issues.
=> Infra > Staking > Rewards Payout mermaid fix

cookie-policy.md, privacy-policy.md, terms-of-use.md
Add placeholder pages for the legal info
goes with: https://github.com/papermoonio/polkadot-mkdocs/pull/54
=> add pages for legal policies and info

develop/parachains/customize-parachain/add-existing-pallets.md, develop/parachains/intro-polkadot-sdk.md
This PR replaces links that pointed to old pages that no longer exist
=> [FIX] - Replace broken links to old sections

polkadot-protocol/basics/randomness.md
=> [FIX] - Typo

develop/index.md, develop/interoperability/test-and-debug.md, develop/parachains/index.md, infrastructure/running-a-node/setup-full-node.md, polkadot-protocol/architecture/polkadot-chain/overview.md, tutorials/index.md, tutorials/interoperability/xcm-transfers/from-relaychain-to-parachain.md, tutorials/polkadot-sdk/index.md, tutorials/polkadot-sdk/parachains/zero-to-hero/pallet-unit-testing.md, tutorials/polkadot-sdk/system-chains/asset-hub/asset-conversion.md, tutorials/polkadot-sdk/testing/spawn-basic-chain.md
This PR updates all of the 404 links
=> update broken links

develop/index.md
This PR just updates the layout of how the information is presented for Learn, Build, etc. for each developer audience
Goes with: https://github.com/papermoonio/polkadot-mkdocs/pull/62
=> update layout of develop index page

tutorials/polkadot-sdk/parachains/zero-to-hero/set-up-a-template.md
=> fix a step in set-up-a-template

tutorials/polkadot-sdk/parachains/zero-to-hero/add-pallets-to-runtime.md
Add a note about where to find prefunded accounts in the zero to hero guide.
=> Add note about prefunded accounts

infrastructure/running-a-validator/onboarding-and-offboarding/set-up-validator.md, infrastructure/running-a-validator/requirements.md
This PR applies the suggested changes in issue #310
=> Fix: Discrepancy in validators minimum requirements

tutorials/polkadot-sdk/parachains/zero-to-hero/add-pallets-to-runtime.md, tutorials/polkadot-sdk/parachains/zero-to-hero/build-custom-pallet.md, tutorials/polkadot-sdk/parachains/zero-to-hero/deploy-to-testnet.md, tutorials/polkadot-sdk/parachains/zero-to-hero/index.md, tutorials/polkadot-sdk/parachains/zero-to-hero/obtain-coretime.md, tutorials/polkadot-sdk/parachains/zero-to-hero/pallet-benchmarking.md, tutorials/polkadot-sdk/parachains/zero-to-hero/pallet-unit-testing.md, tutorials/polkadot-sdk/parachains/zero-to-hero/set-up-a-template.md, tutorials/polkadot-sdk/system-chains/asset-hub/asset-conversion.md, tutorials/polkadot-sdk/system-chains/asset-hub/register-foreign-asset.md, tutorials/polkadot-sdk/system-chains/asset-hub/register-local-asset.md, tutorials/polkadot-sdk/testing/fork-live-chains.md, tutorials/polkadot-sdk/testing/spawn-basic-chain.md
This PR updates admonition use for all pages in the tutorial section.
=> tutorial admonition updates

develop/parachains/deployment/build-deterministic-runtime.md, variables.yml
Solves #334 
Docker Hub: https://hub.docker.com/r/paritytech/srtool/tags
Github Releases: https://github.com/paritytech/srtool/releases
=> update srtool to latest version

develop/interoperability/xcm-runtime-apis.md, llms.txt
This audit was smaller than last month's; I fixed an internal link error that gave a 404. 2 issues were solved this way.
=> Semrush Audit February

llms.txt, tutorials/interoperability/xcm-channels/para-to-para.md, tutorials/interoperability/xcm-channels/para-to-system.md, tutorials/interoperability/xcm-transfers/from-relaychain-to-parachain.md, tutorials/onchain-governance/fast-track-gov-proposal.md, tutorials/polkadot-sdk/parachains/zero-to-hero/obtain-coretime.md, tutorials/polkadot-sdk/parachains/zero-to-hero/pallet-unit-testing.md, tutorials/polkadot-sdk/system-chains/asset-hub/asset-conversion.md
I revise the titles to be more action-oriented.
=> Modify the titles to be more action-oriented

llms.txt, scripts/generate_llms.py
This PR generalizes the script even more and fixes some bugs.
=> Fixes LLMS Script

.snippets/code/develop/smart-contracts/evm-toolkit/ethers-js/checkStorage.js, .snippets/code/develop/smart-contracts/evm-toolkit/ethers-js/compile.js, .snippets/code/develop/smart-contracts/evm-toolkit/ethers-js/deploy.js, .snippets/code/develop/smart-contracts/evm-toolkit/ethers-js/fetchLastBlock.js, .snippets/code/develop/smart-contracts/libraries/viem/Storage.sol, .snippets/code/develop/smart-contracts/libraries/viem/compile.ts, .snippets/code/develop/smart-contracts/libraries/viem/createClient.ts, .snippets/code/develop/smart-contracts/libraries/viem/createWallet.ts, .snippets/code/develop/smart-contracts/libraries/viem/deploy.ts, .snippets/code/develop/smart-contracts/libraries/viem/fetchLastBlock.ts, .snippets/code/develop/smart-contracts/libraries/viem/interact.ts, .snippets/code/develop/smart-contracts/native-evm-contracts/ether-js-server-connection.js, .snippets/code/tutorials/interoperability/xcm-transfers/from-relaychain-to-parachain/reserve-backed-transfer.js, .snippets/code/tutorials/polkadot-sdk/testing/spawn-basic-chain/connect-to-alice-01.js, develop/smart-contracts/libraries/.pages, develop/smart-contracts/libraries/viem.md
This PR adds the Viem documentation to the sc develop section
=> Create "Viem" page for sc develop section

.snippets/code/tutorials/smart-contracts/launch-your-first-project/create-contracts/Storage.sol, tutorials/smart-contracts/launch-your-first-project/create-contracts.md
This PR adds the "Create Contract" tutorial to the sc tutorials section
=> Create "Create Contract" tutorial

llms.txt, tutorials/polkadot-sdk/parachains/zero-to-hero/set-up-a-template.md
=> Omninode Install Fix

.snippets/code/develop/smart-contracts/libraries/web3-py/Storage.sol, .snippets/code/develop/smart-contracts/libraries/web3-py/connect_to_provider.py, .snippets/code/develop/smart-contracts/libraries/web3-py/deploy.py, .snippets/code/develop/smart-contracts/libraries/web3-py/fetch_last_block.py, .snippets/code/develop/smart-contracts/libraries/web3-py/update_storage.py, develop/smart-contracts/libraries/.pages, develop/smart-contracts/libraries/web3-py.md
This PR adds the web3 python library to the Develop > Smart contracts section
=> Document "Web3py" for sc develop section

develop/parachains/deployment/obtain-coretime.md, llms.txt
Any account can pay for on-demand block production. Also, specify that the extrinsic needs to be submitted on the relay chain
=> Update obtain-coretime.md - minor fixes

llms.txt, polkadot-protocol/architecture/system-chains/.pages, polkadot-protocol/architecture/system-chains/people.md
This PR creates the Peope Chain page under Polkadot Protocol > Architecture > System Chains section
=> Add People Chain page 

js/connect-to-metamask.js
This PR adds the metamask.js script to resolve a 404 error on the site, while the devrels are working on the Asset Hub content pages in another branch.
=> Add metamask.js

develop/smart-contracts/connect-to-asset-hub.md
This PR aims to fix the following feedback:
```
Issue: Suggestion; the ending could be more engaging, any call to action, what happens after? Any ending sentence like for example Now that you have test WND tokens, you can use them to deploy and interact with smart contracts on Westend Asset Hub! Any other ideas? 
```
=> Apply feedback on build smart contracts connect to asset hub page

develop/smart-contracts/dev-environments/.pages, develop/smart-contracts/dev-environments/index.md, develop/smart-contracts/libraries/index.md, polkadot-protocol/smart-contract-basics/index.md, tutorials/smart-contracts/index.md, tutorials/smart-contracts/launch-your-first-project/index.md
This PR adds content to the following empty pages:
- develop/smart-contracts/dev-environments/
- develop/smart-contracts/libraries/
- polkadot-protocol/smart-contract-basics/
- tutorials/smart-contracts/
- tutorials/smart-contracts/launch-your-first-project/
=> Create content for each blankindex page in the sc mvp content

llms.txt, tutorials/polkadot-sdk/parachains/zero-to-hero/deploy-to-testnet.md
=> Update deploy-to-testnet.md with chain onboarding note

infrastructure/running-a-validator/index.md, infrastructure/staking-mechanics/index.md, llms.txt
I corrected a few 404 errors that resulted from the recent Wiki update, and I also found a typo in one of the indexes
=> Semrush march report

develop/smart-contracts/libraries/web3-js.md
This PR adds a warning about web3 js sunset - https://blog.chainsafe.io/web3-js-sunset/)%7Btarget=
=> [FIX] - Web3js sunset warning

tutorials/smart-contracts/launch-your-first-project/create-contracts.md
This PR improves the create contracts tutorial according to the received feedback
=> Improve tutorials create contracts page

.snippets/code/develop/smart-contracts/libraries/viem/chainConfig.ts, develop/smart-contracts/libraries/viem.md
This PR addresses the feedback received for the viem page
=> Apply feedback on viem page

develop/smart-contracts/json-rpc-apis.md
This PR addresses the feedback received for the json-rpc page
=> Apply feedback on JSON-RPC page

.snippets/code/tutorials/smart-contracts/launch-your-first-project/create-contracts/Storage.sol, tutorials/smart-contracts/launch-your-first-project/create-contracts.md
Minor fix in create contracts tutorial so next tutorial (hardhat testing and deployment) is doable
=> fix create-contracts.md

tutorials/smart-contracts/launch-your-first-project/create-dapp-ethers-js.md
This PR aims to improve the create a dapp with ethersjs according to the received feedback there
=> Improve tutorials create a dapp with ethersjs

develop/smart-contracts/dev-environments/remix.md
=> Add a banner on the remix ide page

tutorials/smart-contracts/deploy-nft.md
This PR addresses the feedback received in the deploy nft tutorial
=> Improve deoploy nft tutorial - feedback

develop/smart-contracts/dev-environments/index.md, develop/smart-contracts/libraries/index.md
This PR adds web3py and wagmi to the libraries index
=> Fix index libraries

llms.txt, tutorials/polkadot-sdk/parachains/zero-to-hero/set-up-a-template.md
=> Install with --locked (FIX)

tutorials/smart-contracts/launch-your-first-project/create-dapp-ethers-js.md, tutorials/smart-contracts/launch-your-first-project/create-dapp-viem.md
This PR introduces difficulty badges to the smart contracts tutorial sections, which will be shown in cards on both the index and content pages
It needs to be merged with the following: https://github.com/papermoonio/polkadot-mkdocs/pull/86
=> Add difficulty badges post mvp

llms.txt, tutorials/interoperability/xcm-channels/para-to-para.md, tutorials/interoperability/xcm-channels/para-to-system.md, tutorials/interoperability/xcm-transfers/from-relaychain-to-parachain.md, tutorials/onchain-governance/fast-track-gov-proposal.md, tutorials/polkadot-sdk/parachains/zero-to-hero/add-pallets-to-runtime.md, tutorials/polkadot-sdk/parachains/zero-to-hero/build-custom-pallet.md, tutorials/polkadot-sdk/parachains/zero-to-hero/deploy-to-testnet.md, tutorials/polkadot-sdk/parachains/zero-to-hero/obtain-coretime.md, tutorials/polkadot-sdk/parachains/zero-to-hero/pallet-benchmarking.md, tutorials/polkadot-sdk/parachains/zero-to-hero/pallet-unit-testing.md, tutorials/polkadot-sdk/parachains/zero-to-hero/set-up-a-template.md, tutorials/polkadot-sdk/system-chains/asset-hub/asset-conversion.md, tutorials/polkadot-sdk/system-chains/asset-hub/register-foreign-asset.md, tutorials/polkadot-sdk/system-chains/asset-hub/register-local-asset.md, tutorials/polkadot-sdk/testing/fork-live-chains.md, tutorials/polkadot-sdk/testing/spawn-basic-chain.md
In this PR, I added the tag tutorial_badge, where you can add the level of difficulty. It will be displayed both below the title of the content page and in the card of the index of each one.
It needs to be merged with the following: https://github.com/papermoonio/polkadot-mkdocs/pull/86
=> Tutorial badges

llms.txt, tutorials/polkadot-sdk/parachains/zero-to-hero/deploy-to-testnet.md
* Update deploy-to-testnet.md
* Update tutorials/polkadot-sdk/parachains/zero-to-hero/deploy-to-testnet.md
* Update tutorials/polkadot-sdk/parachains/zero-to-hero/deploy-to-testnet.md
---------
=> Update deploy-to-testnet.md (#513)

develop/toolkit/integrations/oracles.md, llms.txt
Chainlink oracle pallet implementation is no longer being maintained. It is archived
=> Remove chainlink reference

develop/smart-contracts/dev-environments/hardhat.md, llms.txt
This PR adds a disclaimer for this current limitation about hardhat and polkavm - https://github.com/paritytech/contract-issues/issues/47#issuecomment-2789769166
=> Fix - hardhat guide disclaimer

develop/smart-contracts/index.md, llms.txt
This PR fixes https://github.com/polkadot-developers/polkadot-docs/issues/545, by rephrasing the first paragraph of the develop smart contracts index
=> [SC Feedback] - Add missing PolkaVM explanation

llms.txt, polkadot-protocol/smart-contract-basics/polkavm-design.md
This PR fixes https://github.com/polkadot-developers/polkadot-docs/issues/550
=> [SC Feedback] - Add architectural design in the polkavm design page

llms.txt, tutorials/smart-contracts/launch-your-first-project/test-and-deploy-with-hardhat.md
Fix usage of variables when installing javascript dependencies
=> Fix usage of variables in Hardhat tutorial

llms.txt, polkadot-protocol/smart-contract-basics/evm-vs-polkavm.md
This PR fixes https://github.com/polkadot-developers/polkadot-docs/issues/554
=> [SC Feedback] - Add digrams to comparing ethereum evm and polkavm

develop/toolkit/api-libraries/py-substrate-interface.md, llms.txt
This minor PR corrects links that were returning a 404 error.
=> April Semrush SEO Report

.snippets/code/tutorials/smart-contracts/launch-your-first-project/create-dapp-viem/ReadContract.tsx, .snippets/code/tutorials/smart-contracts/launch-your-first-project/create-dapp-viem/WalletConnect.tsx, .snippets/code/tutorials/smart-contracts/launch-your-first-project/create-dapp-viem/WriteContract.tsx, llms.txt, tutorials/smart-contracts/launch-your-first-project/create-dapp-ethers-js.md, tutorials/smart-contracts/launch-your-first-project/create-dapp-viem.md, variables.yml
This PR aims to fix the daps tutorials snippets and variables
=> [FIX]  - dapp tutorials

llms.txt, polkadot-protocol/architecture/index.md, polkadot-protocol/architecture/polkadot-chain/.pages, polkadot-protocol/architecture/polkadot-chain/index.md
Rename Polkadot Chain to Polkadot Relay Chain and fix capitalization
=> Fix Polkadot Relay Chain page

develop/light-clients.md
Closes issue #446 
Adds a new page for covering light clients, namely: 
- What they are, along with how they work
- Common implementations and ways of using light clients in Polkadot
=> Light Client Content / Page

llms.txt, tutorials/polkadot-sdk/parachains/zero-to-hero/add-pallets-to-runtime.md
This PR adds a missing title to a code snippet in the zero to hero tutorial
=> Zero to hero quick fix - snippet title 

scripts/generate_llms.py
This PR adds the logic to retry the request to pull remote snippets when getting 429 errors
=> Add retry to llms script

llms.txt, polkadot-protocol/smart-contract-basics/evm-vs-polkavm.md
This PR adds a clarification for the instantiation process in polkavm
=> [Fix]- Evm vs polka vm clarification for instantiation process

tutorials/smart-contracts/launch-your-first-project/create-dapp-ethers-js.md, tutorials/smart-contracts/launch-your-first-project/create-dapp-viem.md
=> add difficulty badges (#515)

.snippets/code/develop/toolkit/api-libraries/dedot/call-runtime-apis.ts, .snippets/code/develop/toolkit/api-libraries/dedot/client-initialization-via-smoldot.ts, .snippets/code/develop/toolkit/api-libraries/dedot/client-initialization-via-ws.ts, .snippets/code/develop/toolkit/api-libraries/dedot/legacy-client-initialization.ts, .snippets/code/develop/toolkit/api-libraries/dedot/pick-chainapi-interface.ts, .snippets/code/develop/toolkit/api-libraries/dedot/runtime-constants.ts, .snippets/code/develop/toolkit/api-libraries/dedot/sign-and-send-tx-with-extension-signer.ts, .snippets/code/develop/toolkit/api-libraries/dedot/sign-and-send-tx-with-keyring.ts, .snippets/code/develop/toolkit/api-libraries/dedot/storage-queries.ts, .snippets/code/develop/toolkit/api-libraries/dedot/subscribe-storage-changes.ts, .snippets/code/develop/toolkit/api-libraries/dedot/watch-on-chain-events.ts, develop/index.md, develop/toolkit/api-libraries/.pages, develop/toolkit/api-libraries/dedot.md, llms.txt
Hello there, 👋
I'd like to submit this PR to add quick instructions for getting started with Dedot to the repo.
[Dedot](https://dedot.dev/) is a next-generation JavaScript client for Polkadot and Polkadot SDK-based blockchains, offering lightweight, tree-shakable APIs with strong TypeScript support.
Dedot is funded through the Web3 Foundation Grants Program and has been adopted by notable projects in the ecosystem, including:
- [Polkadot Live](https://github.com/polkadot-live/polkadot-live-app)
- [Polkadot Staking Dashboard](https://github.com/polkadot-cloud/polkadot-staking-dashboard)
- [Typink](https://github.com/dedotdev/typink)
The documentation includes installation instructions, basic usage examples for connecting to networks, reading on-chain data, and sending transactions.
Looking …
=> feat: add dedot

develop/smart-contracts/connect-to-asset-hub.md, llms.txt
This PR cleans up the endpoints for the connect to AH page, since the only endpoint that implements the eth-rpc adapter is https://westend-asset-hub-eth-rpc.polkadot.io
=> [FIX] - AH endpoints

.snippets/code/develop/toolkit/parachains/quickstart/pop-cli/call-chain.html, .snippets/code/develop/toolkit/parachains/quickstart/pop-cli/new-parachain.html, develop/parachains/customize-parachain/overview.md, infrastructure/running-a-validator/operational-tasks/general-management.md, llms.txt
This PR corrects several issues with external links, including 404 errors, 400 bad requests, and cases where a server with the specified hostname could not be found. These findings result from running the integrity check.
=> SEO May Report fix

develop/parachains/customize-parachain/overview.md, llms.txt
Refactor the page to include two new subsections:
- Solochain Templates
- Parachain Templates
=> Add Solochain Templates and Parachain Templates subsections

develop/parachains/customize-parachain/.pages, develop/parachains/customize-parachain/add-existing-pallets.md, develop/parachains/customize-parachain/add-pallet-instances.md, llms.txt
This page explains how to add multiple instance of the same pallet as requested in #490
=> Add section for instantiable pallets

.snippets/code/tutorials/smart-contracts/launch-your-first-project/test-and-deploy-hardhat/interact-output.html, .snippets/code/tutorials/smart-contracts/launch-your-first-project/test-and-deploy-hardhat/westend-deployment-output.html, llms.txt, tutorials/smart-contracts/launch-your-first-project/test-and-deploy-with-hardhat.md
This PR aims to update the hardhat tutorial according to the `hardhat-polkadot` umbrella package
=> [FIX] - Update hardhat polkadot tutorial

llms.txt, polkadot-protocol/architecture/polkadot-chain/.pages, polkadot-protocol/architecture/polkadot-chain/elastic-scaling.md
Add page that covers elastic scaling
=> Add elastic scaling page

develop/smart-contracts/precompiles/interact-with-precompiles.md, tutorials/smart-contracts/deploy-erc20.md, tutorials/smart-contracts/deploy-nft.md, tutorials/smart-contracts/launch-your-first-project/create-contracts.md, tutorials/smart-contracts/launch-your-first-project/test-and-deploy-with-hardhat.md
This PR updates hardhat tutorials tags to [v0.0.4](https://github.com/polkadot-developers/polkavm-hardhat-examples/tree/v0.0.4)
=> [FIX] - hardhat tutorials tags

develop/parachains/deployment/.pages, develop/parachains/deployment/manage-coretime.md, llms.txt
Add a page explaining the different ways coretime can be used
=> Add manage coretime page

llms.txt, tutorials/smart-contracts/demo-aplications/deploying-uniswap-v2.md
This PR fixes a visual issue in the uniswap tutorial
=> [Fix] - backticks uniswap tutorial

llms.txt, tutorials/smart-contracts/launch-your-first-project/test-and-deploy-with-hardhat.md
This PR adds the following command so the hardhat tutorial works:
```
npm install --legacy-peer-deps @nomicfoundation/hardhat-toolbox 
```
=> [FIX] - hardhat tutorial

llms.txt, polkadot-protocol/smart-contract-basics/networks.md
This PR fixes some wording issues in the SC networks page
=> [FIX] - Quick fix netwoks SC wording

.snippets/code/develop/smart-contracts/dev-environments/hardhat/hardhat.config.js, develop/smart-contracts/dev-environments/hardhat.md, llms.txt, tutorials/smart-contracts/launch-your-first-project/test-and-deploy-with-hardhat.md
This PR fixes a broken link in the hardhat guide and also refactor some hardhat.config files to use hardhat vars instead of dotenv vars
=> [FIX] - hardhat quick fixes

.snippets/code/develop/smart-contracts/dev-environments/hardhat/hardhat.config.js, develop/smart-contracts/dev-environments/hardhat.md, develop/smart-contracts/overview.md, llms.txt, tutorials/smart-contracts/demo-aplications/deploying-uniswap-v2.md, tutorials/smart-contracts/launch-your-first-project/test-and-deploy-with-hardhat.md
This PR cherry picks the following commits:
- 0048a1c29307a796db4137ddcb39081c65ce61ae -> for https://github.com/polkadot-developers/polkadot-docs/pull/695
- 49f22935a19751dba7bb8fada81a782c1b8754ff -> for https://github.com/polkadot-developers/polkadot-docs/pull/685
- f028e308ea45e031d41e645dd354105056f3b2ac -> for https://github.com/polkadot-developers/polkadot-docs/pull/693
=> [FIX] - Cherry pick staging

llms.txt, tutorials/polkadot-sdk/parachains/zero-to-hero/set-up-a-template.md
This PR adds a note and indicates how to set up the correct compiler version for using the parachain template stable2412
=> Add note about compiler version

.snippets/code/develop/parachains/get-started/install-polkadot-sdk/termynal-2.html, develop/parachains/install-polkadot-sdk.md, develop/smart-contracts/local-development-node.md, llms.txt, variables.yml
This PR: 
- Updates Rust installation steps
- Pins a version of the polkadot SDK for local smart contracts node
=> Update rust installation and local contracts node

develop/parachains/maintenance/runtime-upgrades.md, llms.txt
This PR is a follow-up of https://github.com/polkadot-developers/polkadot-docs/pull/713
Thanks to @Zebedeusz
=> Update runtime-upgrades.md - tiny typo

develop/smart-contracts/json-rpc-apis.md, llms.txt
This PR updates eth rpc methods to the json rpc apis guide
=> [FIX] - Update SC rpc methods

develop/smart-contracts/index.md, llms.txt
This small PR removes a duplicate card in `develop/smart-contract/index `
=> Remove Duplicated Card

llms.txt, polkadot-protocol/parachain-basics/blocks-transactions-fees/transactions.md
This PR adds:
- Transaction Mortality
- Unique Identifiers for Extrinsics
=> Add extrinsic content archived in wiki

.snippets/code/develop/smart-contracts/evm-toolkit/ethers-js/compile.js, .snippets/code/develop/smart-contracts/evm-toolkit/libraries/web3-js/compile.js, .snippets/code/develop/smart-contracts/libraries/viem/compile.ts, develop/smart-contracts/libraries/ethers-js.md, develop/smart-contracts/libraries/viem.md, develop/smart-contracts/libraries/web3-js.md, llms.txt, variables.yml
This PR renames and updates references from the @parity/revive js library to @parity/resolc
=> [FIX] -  js library -> resolc for revive

.snippets/text/smart-contracts/polkaVM-warning.md, llms.txt
This pull request makes a small change to `.snippets/text/smart-contracts/polkaVM-warning.md`, updating the label for PolkaVM from "Alpha Release" to "Preview Release" to better reflect its development stage.
=> Update Banner Tittle

.snippets/text/develop/smart-contracts/index/index-timeline.json, develop/smart-contracts/index.md, develop/smart-contracts/overview.md, llms.txt
Resolves https://github.com/polkadot-developers/polkadot-docs/issues/750
This pull request updates references to smart contract development frameworks across multiple files, replacing "Wasm (ink!)" with "Rust (ink!)" to clarify the framework's Rust-based nature and its compatibility with both Wasm and PolkaVM. The changes aim to improve accuracy and consistency in documentation related to Polkadot's smart contract ecosystem.
* [`.snippets/text/develop/smart-contracts/index/index-timeline.json`](diffhunk://#diff-8afcc502de79d63a81c384bbcc18661a42f0b9f7f7fba87718a36de7627fbc06L4-R24): Replaced "Wasm (ink!)" with "Rust (ink!)" in multiple sections, ensuring clarity about the framework's Rust-based nature and its compatibility with Wasm and PolkaVM.
* …
=> Update ink! to reflect Rust instead of Wasm

llms.txt, scripts/generate_llms.py, tutorials/smart-contracts/launch-your-first-project/create-dapp-ethers-js.md, tutorials/smart-contracts/launch-your-first-project/create-dapp-viem.md
Fixes https://github.com/polkadot-developers/polkadot-docs/issues/773
This pull request updates code snippets and references in documentation files to ensure consistency and correctness when integrating wallet connection and contract reading components into dApps. The changes focus on fixing invalid snippet references and improving the clarity of code examples for both `ethers.js` and `viem` implementations.
* Updated snippet references in `llms.txt` for integrating wallet connection and contract reading components in `app/page.js`. [[1]](diffhunk://#diff-f43a9e2f7da89777ca234fc2f236252b27a44652586c9514b243e81bf1b19114R36956-R36958) [[2]](diffhunk://#diff-f43a9e2f7da89777ca234fc2f236252b27a44652586c9514b243e81bf1b19114R37058-R37061)
* Fixed snippet references in …
=> [FIX] - Line numbers in dapps tutorials

develop/smart-contracts/precompiles/xcm-precompile.md, llms.txt
`execute` is the function most people will interact with. It allows almost all types of cross-chain communication.
=> XCM precompile - Stress that `execute` is the real entrypoint

llms-full.txt, tutorials/interoperability/xcm-fee-estimation.md
This pull request refactors and completes the XCM fee estimation tutorial and sample code for teleporting assets from Paseo Asset Hub to Bridge Hub. It improves the clarity and completeness of both the markdown tutorial and the referenced TypeScript sample, ensuring the code snippets are up-to-date, fully functional, and grouped logically by each step in the fee estimation process.
**Key changes by theme:**
* The sample TypeScript code (`teleport-ah-to-bridge-hub.ts`) is now fully implemented with all four steps of XCM fee estimation: local execution, delivery, remote execution, and total aggregation. The code is organized into clear functions, and the main function now demonstrates the complete flow from connection to transaction creation. …
=> [FIX] - Estimation fees line numbers

llms-files/llms-basics.txt, llms-files/llms-dapps.txt, llms-files/llms-infrastructure.txt, llms-files/llms-networks.txt, llms-files/llms-parachains.txt, llms-files/llms-polkadot-protocol.txt, llms-files/llms-smart-contracts.txt, llms-files/llms-tooling.txt, llms-full.txt, tutorials/polkadot-sdk/parachains/zero-to-hero/set-up-a-template.md
Add instructions to install Rust version 1.86.
=> Update Rust setup instructions in template guide
